### ISSUE TITLE
incorrect go version format in go.mod

### ISSUE THREAD

**Issue by 13werwolf13** [ratsky-oss/sshabu#2]
incorrect go version format in go.mod
```
ERROR:obs-service-go_modules:go: errors parsing go.mod:
/tmp/tmp95u9r57k/sshabu-0.1.2/go.mod:3: invalid go version '1.21.0': must match format 1.21
```
Until this is fixed, I cannot packaging a new version into the repository without using patch.

**Comment by alvtsky** [comment]
@13werwolf13 Please confirm if the packaging is now correct. Release v0.1.2 has been reissued, and the problem you encountered should be resolved.

**Comment by 13werwolf13** [comment]
> @13werwolf13 Please confirm if the packaging is now correct. Release v0.1.2 has been reissued, and the problem you encountered should be resolved.

I confirm there is no more this problem.

**Comment by 13werwolf13** [comment]
package for opensuse tumbleweed has been [updated](https://build.opensuse.org/package/show/home:Werwolf2517/sshabu)
